#[package]
#name = "ports"
#version = "0.1.0"
#edition = "2021"

#[dependencies]
#actix-web = "4.0"
#actix-files = "0.6"
#serde = { version = "1.0", features = ["derive"] }
#actix-cors = "0.6.0" 

[package]
name = "hello_server"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.29", features = ["bundled"] }
